# Generated by Django 2.2.2 on 2019-06-06 11:42

import app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to=app.models.user_directory_path)),
                ('date_of_birth', models.DateField(null=True)),
                ('company_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_address_is', to='app.Address')),
                ('friends', models.ManyToManyField(related_name='friends_are', to=settings.AUTH_USER_MODEL)),
                ('permanent_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address_is', to='app.Address')),
                ('street_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='street_address_is', to='app.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
